content/urls.py
from django.urls import path
from content.views import (
    create_content_view,
    detail_content_view,
    edit_content_view,

)

app_name = 'content'

urlpatterns = [
    path('create/', create_content_view, name='create'),
    path('<slug>/', detail_content_view, name='detail'),
    path('<slug>/edit/', edit_content_view, name='edit'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

from mysite import settings
from projects.views import (
    home_screen_view,
)


from account.views import (
    registration_view,
    logout_view,
    login_view,
    account_view,
    must_authenticate_view,
)

urlpatterns = [
    path('', home_screen_view, name='home'),
    path('account/', account_view, name='account'),
    path('admin/', admin.site.urls),
    path('content/', include('content.urls', 'content')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('must_authenticate/', must_authenticate_view, name='must_authenticate'),
    path('register/', registration_view, name='register'),

    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
         name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'),
         name='password_change'),

    path('password_reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/models.py
from django.db import models

# Create your models here.

projects/views.py
from django.shortcuts import render
from operator import attrgetter
from content.models import ContentPost
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator

from content.views import get_content_queryset

CONTENT_POST_PER_PAGE = 10

# Create your views here.

def home_screen_view(request, *args, **kwargs):
    context = {}

    # Search
    query = ""
    if request.GET:
        query = request.GET.get('q', '')
        context['query'] = str(query)

    content_posts = sorted(get_content_queryset(query), key=attrgetter('date_updated'), reverse=True)


    page = request.GET.get('page', 1)
    content_posts_paginator = Paginator(content_posts, CONTENT_POST_PER_PAGE)
    try:
        content_posts = content_posts_paginator.page(page)
    except PageNotAnInteger:
        content_posts = content_posts_paginator.page(BLOG_POSTS_PER_PAGE)
    except EmptyPage:
        content_posts = content_posts_paginator.page(blog_posts_paginator.num_pages)

    context['content_posts'] = content_posts

    return render(request, "projects/home.html", context)

projects/templates/projects/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style type="text/css">

	@media (max-width: 768px) {
		.right-column{
			margin-left: 0px;
		}
	}

	@media (min-width: 768px) {
		.right-column{
			margin-left: 20px;
		}
	}

	.blog-post-container{
		margin-bottom: 20px;
		width: 100%;
        margin-top: 50px;
	}
	.create-post-bar{
		background-color: #fff;
		margin-bottom:20px;
        margin-top: 50px;
	}

	.left-column{
		padding:0px;
	}

	.right-column{
		padding:0px;
	}
	.lead{
		font-size: 17px;
	}
</style>


<!-- main content -->
<div class="container">
	<div class="row">

		<!-- content feed -->
		<div class="left-column col-lg-7 offset-lg-1">

			<!-- Top 'create post' bar -->
			<div class="d-lg-none mb-3">
				<div class="card m-auto d-flex flex-column p-3">
					<img class="img-fluid d-block m-auto pb-2" src="{% static 'barbie-logo.png' %}" width="72" height="72">
					<p class="lead">WEB</p>
					<p class="m-auto"><a class="btn btn-primary" href="{% url 'content:create' %}">Create post</a></p>
				</div>
			</div>
			<!-- end Top 'create post' bar -->

			<!-- Content posts-->
			{% if content_posts %}
				{% for post in content_posts %}
					<div class="blog-post-container">
						{% include 'content/snippets/content_post_snippet.html' with content_post=post %}
					</div>
				{% endfor %}
			{% else %}
				<div class="blog-post-container">
					{% include 'content/snippets/content_post_snippet.html' with query=query %}
				</div>
			{% endif %}
			<!-- End Blog posts-->

		<!-- Pagination -->
		{% include 'content/snippets/content_post_pagination.html' with content_posts=content_posts %}

		</div>
		<!-- end blog feed -->


		<!-- Right 'create post' column  -->
		<div class="right-column col-lg-3 d-lg-flex d-none flex-column">

			<div class="card create-post-bar d-flex flex-column p-3">
				<img class="img-fluid d-block m-auto pb-2" src="{% static 'barbie-logo.png' %}" width="72" height="72">
				<p class="lead">Built By Django Framework.</p>
				<p class="m-auto"><a class="btn btn-primary" href="{% url 'content:create' %}">Create post</a></p>
			</div>

		</div>
		<!-- end Right 'create post' column  -->



	</div>
</div>

{% endblock content %}