content/urls.py
from django.urls import path
from content.views import (
    create_content_view,
    detail_content_view,
    edit_content_view,

)

app_name = 'content'

urlpatterns = [
    path('create/', create_content_view, name='create'),
    path('<slug>/', detail_content_view, name='detail'),
    path('<slug>/edit/', edit_content_view, name='edit'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

from mysite import settings
from projects.views import (
    home_screen_view,
)


from account.views import (
    registration_view,
    logout_view,
    login_view,
    account_view,
    must_authenticate_view,
)

urlpatterns = [
    path('', home_screen_view, name='home'),
    path('account/', account_view, name='account'),
    path('admin/', admin.site.urls),
    path('content/', include('content.urls', 'content')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('must_authenticate/', must_authenticate_view, name='must_authenticate'),
    path('register/', registration_view, name='register'),

    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
         name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'),
         name='password_change'),

    path('password_reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

content/models.py
from django.db import models
from django.utils.text import slugify
from django.conf import settings
from django.db.models.signals import post_delete, pre_save
from django.dispatch import receiver

def upload_location(instance, filename, **kwargs):
    file_path = 'content/{author_id}/{title}-{filename}'.format(
        author_id=str(instance.author.id), title=str(instance.title), filename=filename
        )
    return file_path

class ContentPost(models.Model):
    title                   = models.CharField(max_length=50, null=False, blank=False)
    body                    = models.TextField(max_length=5000, null=False, blank=False)
    image                   = models.ImageField(upload_to=upload_location, null=False, blank=False)
    date_published          = models.DateTimeField(auto_now_add=True, verbose_name="date published")
    date_updated            = models.DateTimeField(auto_now_add=True, verbose_name="date updated")
    author                  = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    slug                    = models.SlugField(blank=True, unique=True)

    def __str__(self):
        return self.title

@receiver(post_delete, sender=ContentPost)
def submission_delete(sender, instance, **kwargs):
    instance.image.delete(False)

def pre_save_content_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.author.username + "-" + instance.title)

pre_save.connect(pre_save_content_post_receiver, sender=ContentPost)

content/forms.py
from django import forms
from content.models import ContentPost


class CreateContentPostForm(forms.ModelForm):

	class Meta:
		model = ContentPost
		fields = ['title', 'body', 'image']

class UpdateContentPostForm(forms.ModelForm):

	class Meta:
		model = ContentPost
		fields = ['title', 'body', 'image']

	def save(self, commit=True):
		content_post = self.instance
		content_post.title = self.cleaned_data['title']
		content_post.body = self.cleaned_data['body']

		if self.cleaned_data['image']:
			content_post.image = self.cleaned_data['image']

		if commit:
			content_post.save()
		return content_post

content/views.py
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404

from content.models import ContentPost
from content.forms import CreateContentPostForm, UpdateContentPostForm
from account.models import Account

def create_content_view(request):

    context = {}

    user = request.user
    if not user.is_authenticated:
        return redirect('must_authenticate')

    form = CreateContentPostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        obj = form.save(commit=False)
        author = Account.objects.filter(email=user.email).first()
        obj.author = author
        obj.save()
        form = CreateContentPostForm()

    context['form'] = form

    return render(request, "content/create_content.html", context)

def detail_content_view(request, slug):

    context ={}

    content_post = get_object_or_404(ContentPost, slug=slug)
    context['content_post'] = content_post

    return render(request, 'content/detail_content.html', context)


def edit_content_view(request, slug):

    context = {}

    user = request.user
    if not user.is_authenticated:
        return redirect('must_authenticate')

    content_post = get_object_or_404(ContentPost, slug=slug)
    if request.POST:
        form = UpdateContentPostForm(request.POST or None, request.FILES or None, instance=content_post)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.save()
            context['success_message'] = "Updated Successfully"
            content_post = obj

    form = UpdateContentPostForm(
        initial = {
            "title": content_post.title,
            "body": content_post.body,
            "image": content_post.image,
        }
    )
    context['form'] = form
    return render(request, 'content/edit_content.html', context)

def get_content_queryset(query=None, slug=None):
    queryset = []
    queries = query.split(" ")
    for q in queries:
        posts = ContentPost.objects.filter(
            Q(title__icontains=q) |
            Q(body__icontains=q)
        ).distinct()

        for post in posts:
            queryset.append(post)
    return list(set(queryset))

content/templates/content/snippets/content_post_pagination.html
<!-- FILTERED Pagination -->
<div class="d-flex flex-column m-auto pagination mt-5">
<nav aria-label="Page navigation">
<ul class="pagination pg-grey justify-content-center">
	{% if content_posts.has_previous %}
        <li class="page-item">
		  <a class="page-link" href="?{% if query %}q={{query}}&{% endif %}page={{ content_posts.previous_page_number }}">&laquo; Previous</a>
		</li>
    {% endif %}

	{% for i in content_posts.paginator.page_range %}
		{% if blog_posts.number == i %}
			<li class="page-item active"><a class="page-link">{{ i }}</a></li>
		{% else %}
			<li class="page-item" ><a class="page-link" href="?{% if query %}q={{query}}&{% endif %}page={{ i }}">{{ i }}</a></li>
		{% endif %}
	{% endfor %}

    {% if content_posts.has_next %}
    	<li class="page-item">
		  <a class="page-link" href="?{% if query %}q={{query}}&{% endif %}page={{ content_posts.next_page_number }}">Next</a>
		</li>
		<li class="page-item">
		  <a class="page-link"  href="?{% if query %}q={{query}}&{% endif %}page={{ content_posts.paginator.num_pages }}">Last &raquo;</a>
		</li>
    {% endif %}
</ul>
</nav>
</div>
<!-- end pagination-->

content/templates/content/snippets/content_post_snippet.html
<style type="text/css">
	.card{
		max-width: 700px;
		width: 100%;
	}
	.card-body{
		padding: 20px;
	}
</style>

{% if content_post %}
<div class="container">
	<div class="row">
		<!-- Content Post -->
		<div class="card m-auto">
			<a href="{% url 'content:detail' post.slug %}">
				<img class="card-img-top" src="{{content_post.image.url}}">
			</a>
			<div class="card-body mt-2 mb-2">
				<a href="{% url 'content:detail' post.slug %}">
					<h2 class="card-title">{{content_post.title}}</h2>
				</a>
				<p class="card-text">{{content_post.body|safe|truncatechars:180}}</p>
				{% if blog_post.author == request.user %}
					<a href="{% url 'content:edit' content_post.slug %}" class="btn btn-primary">Update</a>
				{% endif %}
			</div>
			<div class="card-footer text-muted">
			  Updated on {{content_post.date_updated}} by {{content_post.author}}
			</div>
		</div>
	</div>
</div>

{% else %}

<div class="container">
	<div class="row">
		<div class="card m-auto">
			<div class="card-body mt-2 mb-2">
				<h2 class="card-title">No results</h2>
				<p class="card-text">There were no results matching the search: "{{query}}"</p>
			</div>
		</div>
	</div>
</div>

{% endif %}